defaults: &defaults
  adapter: postgresql
  encoding: unicode
  pool: 20
  username: <%= ENV['POSTGRES_USERNAME'] || ENV['USER'] %>

development:
  database: profile_buddy_dev
  <<: *defaults

test:
  database: profile_buddy_test
  <<: *defaults

staging:
  database: profile_buddy_staging
  <<: *defaults

production:
  database: profile_buddy_prod
  <<: *defaults
